spring:
  datasource:
    url: jdbc:mysql://34.68.210.179:3306/test_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql은 system.out.print로 찍힌다. 운영에서는 로그로
#        찍어야하므로 org.hibernate.SQL: debug를 사용해야 하므로 주석처리
#        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug

#    --- p6spy ---
#    이 프로젝트에는 외부 라이브러리인 p6spy 사용
#    p6spy 적용은 운영에서는 성능에 문제가 있을 수 있으므로
#    성능테스트 후 적용 또는 개발 부분에서만 사용

#    로그에 쿼리 파라미터를 찍어준다.
#    org.hibernate.type: trace

