export const board = [
  {
    id: 'id1',
    content: 'content1',
    detail_content: 'detail_content1',
    service_area: 'service_area1',
    theme_type: 'theme_type1',
    title: 'title1',
    views: 'views1',
  },
  {
    id: 'id2',
    content: 'content2',
    detail_content: 'detail_content2',
    service_area: 'service_area2',
    theme_type: 'theme_type2',
    title: 'title2',
    views: 'views2',
  },
  {
    id: 'id3',
    content: 'content3',
    detail_content: 'detail_content3',
    service_area: 'service_area3',
    theme_type: 'theme_type3',
    title: 'title3',
    views: 'views3',
  },
  {
    id: 'id4',
    content: 'content4',
    detail_content: 'detail_content4',
    service_area: 'service_area4',
    theme_type: 'theme_type4',
    title: 'title4',
    views: 'views4',
  },
  {
    id: 'id5',
    content: 'content5',
    detail_content: 'detail_content5',
    service_area: 'service_area5',
    theme_type: 'theme_type5',
    title: 'title5',
    views: 'views5',
  },
];

export const users = [
  {
    name: 'name1',
    role: 'role1',
    city: 'city1',
    street: 'street1',
    zipcode: 'zipcode1',
    id: 'id1',
    password: 'password1',
  },
  {
    name: 'name2',
    role: 'role2',
    city: 'city2',
    street: 'street2',
    zipcode: 'zipcode2',
    id: 'id2',
    password: 'password2',
  },
  {
    name: 'name3',
    role: 'role3',
    city: 'city3',
    street: 'street3',
    zipcode: 'zipcode3',
    id: 'id3',
    password: 'password3',
  },
];

export const comments = [
  {
    id: 'id1',
    author: 'author1',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam odio tortor, ullamcorper quis justo ut, tincidunt ultrices massa. Fusce et lacinia elit. Nulla euismod hendrerit urna, in efficitur risus suscipit sit amet. Vivamus nunc neque, sodales vel hendrerit vel, tincidunt et neque. Nam leo mauris, ultrices vitae luctus malesuada, consequat ac libero. Duis congue nibh non rutrum dictum.',
    createdAt: '2020.11.20.18:19:16',
  },
  {
    id: 'id2',
    author: 'author2',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam odio tortor, ullamcorper quis justo ut, tincidunt ultrices massa. Fusce et lacinia elit. Nulla euismod hendrerit urna, in efficitur risus suscipit sit amet. Vivamus nunc neque, sodales vel hendrerit vel, tincidunt et neque. Nam leo mauris, ultrices vitae luctus malesuada, consequat ac libero. Duis congue nibh non rutrum dictum.',
    createdAt: '2020.11.20.18:19:16',
  },
  {
    id: 'id3',
    author: 'author3',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam odio tortor, ullamcorper quis justo ut, tincidunt ultrices massa. Fusce et lacinia elit. Nulla euismod hendrerit urna, in efficitur risus suscipit sit amet. Vivamus nunc neque, sodales vel hendrerit vel, tincidunt et neque. Nam leo mauris, ultrices vitae luctus malesuada, consequat ac libero. Duis congue nibh non rutrum dictum.',
    createdAt: '2020.11.20.18:19:16',
  },
  {
    id: 'id4',
    author: 'author4',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam odio tortor, ullamcorper quis justo ut, tincidunt ultrices massa. Fusce et lacinia elit. Nulla euismod hendrerit urna, in efficitur risus suscipit sit amet. Vivamus nunc neque, sodales vel hendrerit vel, tincidunt et neque. Nam leo mauris, ultrices vitae luctus malesuada, consequat ac libero. Duis congue nibh non rutrum dictum.',
    createdAt: '2020.11.20.18:19:16',
  },
  {
    id: 'id5',
    author: 'author5',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam odio tortor, ullamcorper quis justo ut, tincidunt ultrices massa. Fusce et lacinia elit. Nulla euismod hendrerit urna, in efficitur risus suscipit sit amet. Vivamus nunc neque, sodales vel hendrerit vel, tincidunt et neque. Nam leo mauris, ultrices vitae luctus malesuada, consequat ac libero. Duis congue nibh non rutrum dictum.',
    createdAt: '2020.11.20.18:19:16',
  },
];
